# Generated by Django 3.1.3 on 2020-12-01 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9]+')]),
        ),
    ]
