# Generated by Django 3.1.4 on 2020-12-01 15:58

import django.core.validators
from django.db import migrations, models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20201201_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(validators=[event.validators.validate_end_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(validators=[event.validators.validate_start_date]),
        ),
    ]
