# Generated by Django 3.1.4 on 2020-12-03 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201201_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.IntegerField(choices=[(1, 'ALTO'), (2, 'MEDIO'), (3, 'BASSO')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]+$')]),
        ),
    ]
