# Generated by Django 3.1.4 on 2020-12-03 14:44

from django.db import migrations, models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20201203_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.IntegerField(choices=[(1, 'LAVORO'), (2, 'SVAGO'), (3, 'FAMIGLIA'), (4, 'SCUOLA')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(validators=[event.validators.validate_start_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(choices=[(1, 'ALTO'), (2, 'MEDIO'), (3, 'BASSO')]),
        ),
    ]
