# Generated by Django 3.1.3 on 2020-12-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201203_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.IntegerField(choices=[(0, 'ALTO'), (1, 'MEDIO'), (2, 'BASSO')]),
        ),
    ]
