# Generated by Django 3.1.3 on 2020-12-04 00:57

from django.db import migrations, models
import event.validators


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20201203_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(validators=[event.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(validators=[event.validators.validate_date]),
        ),
    ]
